// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./useAsyncMemo.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "useAsyncMemo.ts", path: "hooks/others/useAsyncMemo.ts", demos: demos || [] };

export default mod;
