// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./useIsSticky.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "useIsSticky.ts", path: "hooks/others/useIsSticky.ts", demos: demos || [] };

export default mod;
