// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./useRange.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "useRange.tsx", path: "hooks/others/useRange.tsx", demos: demos || [] };

export default mod;
