// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./Dial.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "Dial.tsx", path: "components/layout/Dial.tsx", demos: demos || [] };

export default mod;
