// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./GridCols.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "GridCols.tsx", path: "components/layout/GridCols.tsx", demos: demos || [] };

export default mod;
