// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./Popover.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "Popover.tsx", path: "components/layout/Popover.tsx", demos: demos || [] };

export default mod;
