// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./useAsSet.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "useAsSet.ts", path: "hooks/iterables/useAsSet.ts", demos: demos || [] };

export default mod;
