// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./useArray.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "useArray.ts", path: "hooks/iterables/useArray.ts", demos: demos || [] };

export default mod;
