// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./BreakpointsProvider.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "BreakpointsProvider.tsx", path: "contexts/BreakpointsProvider.tsx", demos: demos || [] };

export default mod;
