// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./BroadCast.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "BroadCast.tsx", path: "components/others/BroadCast.tsx", demos: demos || [] };

export default mod;
