// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./StorageProvider.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "StorageProvider.tsx", path: "components/others/StorageProvider.tsx", demos: demos || [] };

export default mod;
