// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./Search.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "Search.tsx", path: "components/inputs/Search.tsx", demos: demos || [] };

export default mod;
