// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./AlertTitle.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "AlertTitle.tsx", path: "components/alerts/AlertTitle.tsx", demos: demos || [] };

export default mod;
