// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./ErrorAlert.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "ErrorAlert.tsx", path: "components/alerts/ErrorAlert.tsx", demos: demos || [] };

export default mod;
