// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./HighlightText.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "HighlightText.tsx", path: "components/text/HighlightText.tsx", demos: demos || [] };

export default mod;
