// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./WithUnit.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "WithUnit.tsx", path: "components/text/WithUnit.tsx", demos: demos || [] };

export default mod;
