// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./useInterval.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "useInterval.ts", path: "hooks/document/useInterval.ts", demos: demos || [] };

export default mod;
