// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./useTimeout.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "useTimeout.ts", path: "hooks/document/useTimeout.ts", demos: demos || [] };

export default mod;
