// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./input-helpers.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "input-helpers.ts", path: "input-helpers.ts", demos: demos || [] };

export default mod;
