// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./setup.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "setup.ts", path: "setup.ts", demos: demos || [] };

export default mod;
