// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./timing.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "timing.ts", path: "timing.ts", demos: demos || [] };

export default mod;
