// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./types.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "types.ts", path: "types.ts", demos: demos || [] };

export default mod;
