// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./Input.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "Input.tsx", path: "components/input/base/Input.tsx", demos: demos || [] };

export default mod;
