// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./RadioButtons.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "RadioButtons.tsx", path: "components/input/base/RadioButtons.tsx", demos: demos || [] };

export default mod;
