// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./TextArea.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "TextArea.tsx", path: "components/input/base/TextArea.tsx", demos: demos || [] };

export default mod;
