// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./CodeInput.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "CodeInput.tsx", path: "components/input/CodeInput.tsx", demos: demos || [] };

export default mod;
