// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./JSForm.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "JSForm.tsx", path: "components/input/form/JSForm.tsx", demos: demos || [] };

export default mod;
