// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./Badge.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "Badge.tsx", path: "components/data-display/Badge.tsx", demos: demos || [] };

export default mod;
