// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./Chip.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "Chip.tsx", path: "components/data-display/Chip.tsx", demos: demos || [] };

export default mod;
