// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./InfoCard.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "InfoCard.tsx", path: "components/data-display/InfoCard.tsx", demos: demos || [] };

export default mod;
