// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./Labelize.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "Labelize.tsx", path: "components/data-display/Labelize.tsx", demos: demos || [] };

export default mod;
