// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./Markdown.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "Markdown.tsx", path: "components/data-display/Markdown.tsx", demos: demos || [] };

export default mod;
