// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./Todo.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "Todo.tsx", path: "components/dev/Todo.tsx", demos: demos || [] };

export default mod;
