// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./index.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "index.ts", path: "components/navigation/index.ts", demos: demos || [] };

export default mod;
