// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./TreeViewItem.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "TreeViewItem.tsx", path: "components/navigation/TreeViewItem.tsx", demos: demos || [] };

export default mod;
