// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./LargeDrawer.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "LargeDrawer.tsx", path: "components/drawers/LargeDrawer.tsx", demos: demos || [] };

export default mod;
