// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./GrowV.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "GrowV.tsx", path: "components/transitions/GrowV.tsx", demos: demos || [] };

export default mod;
