// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./SomeTransition.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "SomeTransition.tsx", path: "components/transitions/SomeTransition.tsx", demos: demos || [] };

export default mod;
