// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./PageBar.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "PageBar.tsx", path: "components/page/PageBar.tsx", demos: demos || [] };

export default mod;
