// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./Page.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "Page.tsx", path: "components/page/Page.tsx", demos: demos || [] };

export default mod;
