// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./tabs.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "tabs.tsx", path: "components/navigation/tabs/tabs.tsx", demos: demos || [] };

export default mod;
