// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./Loading.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "Loading.tsx", path: "components/feedback/Loading.tsx", demos: demos || [] };

export default mod;
