// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./Placeholder.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "Placeholder.tsx", path: "components/feedback/Placeholder.tsx", demos: demos || [] };

export default mod;
