// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./ProgressError.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "ProgressError.tsx", path: "components/feedback/ProgressError.tsx", demos: demos || [] };

export default mod;
