// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./ProgressSuccess.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "ProgressSuccess.tsx", path: "components/feedback/ProgressSuccess.tsx", demos: demos || [] };

export default mod;
