// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./ButtonSpinner.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "ButtonSpinner.tsx", path: "components/buttons/ButtonSpinner.tsx", demos: demos || [] };

export default mod;
