// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./ToggleIconButtonGroup.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "ToggleIconButtonGroup.tsx", path: "components/buttons/ToggleIconButtonGroup.tsx", demos: demos || [] };

export default mod;
