// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./LoadingDialog.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "LoadingDialog.tsx", path: "components/dialogs/LoadingDialog.tsx", demos: demos || [] };

export default mod;
