// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./stat.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "stat.tsx", path: "components/data-display/stats/stat.tsx", demos: demos || [] };

export default mod;
