// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./useSet.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "useSet.ts", path: "hooks/iterable/useSet.ts", demos: demos || [] };

export default mod;
