// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./BlankButton.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "BlankButton.tsx", path: "components/input/buttons/BlankButton.tsx", demos: demos || [] };

export default mod;
