// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./Button.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "Button.tsx", path: "components/input/buttons/Button.tsx", demos: demos || [] };

export default mod;
