// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./ToggleButtonGroup.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "ToggleButtonGroup.tsx", path: "components/input/buttons/ToggleButtonGroup.tsx", demos: demos || [] };

export default mod;
