// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./DialogTitle.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "DialogTitle.tsx", path: "components/dialogs/dialog/DialogTitle.tsx", demos: demos || [] };

export default mod;
