// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./Live.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "Live.tsx", path: "components/data-display/badges/Live.tsx", demos: demos || [] };

export default mod;
