// auto generated by script 'demo-prepare'

import type { ModuleDef, DemoDef } from "src/types";

const demos: DemoDef[] = Object.values(import.meta.glob("./Avatars.demo*.tsx", { import: "default", eager: true }));

const mod: ModuleDef = { name: "Avatars.tsx", path: "components/data-display/avatars/Avatars.tsx", demos: demos || [] };

export default mod;
